### ISSUE TITLE
[Dashboard] Per District Results Status (as data is coming to the system)

### ISSUE THREAD

**Issue by dinukadesilva** [ECLK/results-tabulation#219]
- Total for district
	- Voter turnout:
		- Total registered voters
		- Total polled
		- Total registered postal votes
		- Total postal votes received
	- Results
		- Votes per candidate (sorted most votes to least)
- By polling division
	- Voter turnout:
		- Total registered voters
		- Total polled
	- Results
		- Votes per candidate
	- Counting centers
		- Total
		- Completed
		- Pending
- List of 5 polling divisions that are closest to finishing (if district is not yet complete)
- Setup to auto rotate to latest released district
- Can manually select a district

**Comment by sanjiva** [comment]
Closing as this is now done. If there are problems / enhancements we will create specific issues.
