### ISSUE TITLE
Push box count results to result-dist endpoint at PD/ED/Country levels

### ISSUE THREAD

**Issue by sanjiva** [ECLK/results-tabulation#231]
As a box count result is committed (confirmed), please post the result in the following JSON format to a URL that I'll put below soon:

```
{
  “timestamp”: string,
  “type”: string,
  “ed_code”: string,
  “ed_name”: string,
  “pd_code”: string,
  “pd_name”: string,
  “valid”: number,
  “rejected”: number,
  “polled”: number,
  “electors”: number 
}
```

The “type” indicates the level of the result. The values are: “NATIONAL”, “ELECTORAL-DISTRICT”, “POLLING-DIVISION”. For national level results, the “ed_*” and “pd_*” properties will not be present. For electoral level results, the “pd_*” properties will not be present.

If codes are not yet available just put "XX" into those for now.

**Comment by dinukadesilva** [comment]
@sanjiva
There's a box count only at the counting centre level and it doesn't agregated into any PD, ED or national reports.

**Comment by sanjiva** [comment]
No that's not right .. they do release it at all the different levels. I'm not sure what the verification / release process is but they do release it at all levels.

See https://drive.google.com/drive/folders/1pHp23hWdblRK4QRSWmeUuyn6IRy9hC6I and look at https://drive.google.com/drive/folders/18f7QVErk8WvmJMEGCkK5uX6sby114xtK and in there the file 11AS.txt - that the summary box count for electoral district district 11, polling division A.

**Comment by sanjiva** [comment]
I'm changing the format a bit to have a type of result property:
```
{
  “type”: “SUMMARY”,
  “timestamp”: string,
  “level”: string,
  “ed_code”: string,
  “ed_name”: string,
  “pd_code”: string,
  “pd_name”: string,
  “valid”: number,
  “rejected”: number,
  “polled”: number,
  “electors”: number 
}
```

**Comment by sanjiva** [comment]
I had misunderstood this data - these are not from box counts but rather summary data for the same 41 results shown by quality of vote instead of party-wise. 

So I'll close this issue.
