### ISSUE TITLE
Push party-wise results to result-dist endpoint at PD/ED/Country levels

### ISSUE THREAD

**Issue by sanjiva** [ECLK/results-tabulation#232]
As a party-wise result is committed (confirmed), please post the result in the following JSON format to a URL that I'll put below soon:

```
{
  “timestamp”: string,
  “type”: string,
  “ed_code”: string,
  “ed_name”: string,
  “pd_code”: string,
  “pd_name”: string,
  “by_party”: [
    {
      “party”: string,
      “votes”: number,
      “percentage”: number
    },
    ...
  ]
}
```

The “type” indicates the level of the result. The values are: “NATIONAL”, “ELECTORAL-DISTRICT”, “POLLING-DIVISION”. For national level results, the “ed_*” and “pd_*” properties will not be present. For electoral level results, the “pd_*” properties will not be present.

The “by_party” property value is an array of objects with each object showing the votes received by a particular party. For the 2019 Presidential election there will be 35 items in that array. The parties sorting order varies based on the level of the result (polling division vs. electoral district etc.) and is indicated with the file name convention.

The “votes” values will be a JSON number as an integer. The “percentage” number will be a JSON number as a decimal with 2 digits after the decimal point.

If codes are not yet available just put "XX" into those for now.

**Comment by dinukadesilva** [comment]
@sanjiva
What is the code here. Is it the ID. (Eg. polling division id)

**Comment by sanjiva** [comment]
Each PD has an ID like 01A (meaning electoral district code "01" and polling division code "A"). 

What I meant is the "01" (as "ed_code") and the "A" (as "pd_code") separated.

**Comment by sanjiva** [comment]
I'm changing the format slightly by adding another property on top to say that this is a party result:
```
{
  “type”: “PARTY”,
  “timestamp”: string,
  “level”: string,
  “ed_code”: string,
  “ed_name”: string,
  “pd_code”: string,
  “pd_name”: string,
  “by_party”: [
    {
      “party”: string,
      “votes”: number,
      “percentage”: number
    },
    ...
  ]
}
```
