### ISSUE TITLE
Map privileges of each role for tally sheet flows and reports 

### ISSUE THREAD

**Issue by nshamit** [ECLK/results-tabulation#279]
Created a list. @sanjiva  @dinukadesilva @umayangag, please add more scenarios. 

- [ ] unlock only w/ PD verifier role for tally sheets. Grey out/ deactivate unlock for data entry/verifier roles lower than PD verifier. 

- [ ] data entry can verify a form entered by another person

- [ ] verifier can enter data for a form entered by another person

- [ ] pd verifier must unlock for editing to take place on a form w/ an error. dataeditor must be a different person from the person who verified. 

- [ ] pd verifier can also view

- [ ] not all pd viewers can verify

- [ ] dataeditors can be pd viewers, not pd verifiers

- [ ] ed verifier can also view

- [ ] not all ed viewers can verify

**Comment by sanjiva** [comment]
Closing issue as this has been done.
