### ISSUE TITLE
when printing a report or any summary view, the name of the person who pressed the print button is recorded 

### ISSUE THREAD

**Issue by nshamit** [ECLK/results-tabulation#283]
- when printing a report or any summary view, the name of the person who pressed the print button is recorded 
- this should be recorded at the bottom of the page

**Comment by callkalpa** [comment]
We already have the username, timestamp and barcode printed at the footer of each page of reports. With the above PR I just added a label for the username to make it more clear.

What is summary view, is it the html view of data entry tally sheets, PRE-41 for example?
