### ISSUE TITLE
Tallysheet Model - PE-R2

### ISSUE THREAD

**Issue by sm1990** [ECLK/results-tabulation#427]
This include seat calculation and draft visualization

**Comment by dinukadesilva** [comment]
![15831485618962844634242492126392](https://user-images.githubusercontent.com/10680296/75672655-3499a600-5ca7-11ea-82c8-8229774f84cc.jpg)
![15831485835282386628705746387319](https://user-images.githubusercontent.com/10680296/75672679-3fecd180-5ca7-11ea-8d88-22728211e028.jpg)
