### ISSUE TITLE
Tallysheet Report - Polling Division Results

### ISSUE THREAD

**Issue by sm1990** [ECLK/results-tabulation#450]

**Comment by dinukadesilva** [comment]
![1583146493659697044465435715210](https://user-images.githubusercontent.com/10680296/75670240-63f9e400-5ca2-11ea-8f78-00f8c053c696.jpg)
![15831465280386807927499998417876](https://user-images.githubusercontent.com/10680296/75670282-7542f080-5ca2-11ea-95f3-14b889bddb52.jpg)
