### ISSUE TITLE
Tally sheet report PE-39

### ISSUE THREAD

**Issue by dinukadesilva** [ECLK/results-tabulation#476]

**Comment by dinukadesilva** [comment]
@sm1990 This is ready to be started. New election is required to be created to reflect the changes unless you are already on a latest.

**Comment by callkalpa** [comment]
Report: https://github.com/ECLK/results-tabulation-api/issues/474#issuecomment-592418807

**Comment by dinukadesilva** [comment]
@callkalpa 
The order of invalid vote categories are not the same at the data entry and report. It has to the order that is there in the manual always.
<img width="1438" alt="Screenshot 2020-03-07 at 7 50 22 PM" src="https://user-images.githubusercontent.com/10680296/76145162-0bb15080-60ad-11ea-829d-4ed8197000cf.png">
<img width="1439" alt="Screenshot 2020-03-07 at 7 50 36 PM" src="https://user-images.githubusercontent.com/10680296/76145163-0f44d780-60ad-11ea-923b-62c411130464.png">
