### ISSUE TITLE
Auth app sign in url not correctly redirected in Dev 

### ISSUE THREAD

**Issue by dinukadesilva** [ECLK/results-tabulation#519]
Steps to reproduce
- Log in with any valid credentials
- Log out

And then it keep on waiting in Loading page. Even refreshing the page not working unless all cache and cookies are deleted from the browser.

**Comment by dinukadesilva** [comment]
This looks like happening due to a miss in routing. I have posted a question on react-router to get some support.
https://github.com/ReactTraining/react-router/issues/7191

**Comment by dinukadesilva** [comment]
https://stackoverflow.com/questions/60663690/how-to-disable-anonymous-urls-hitting-the-application

**Comment by dinukadesilva** [comment]
@kosalag I couldn't find a correct answer to this yet. But, having different urls for the tabulation app and the auth app is ideally fixing this issue. Can we do that?

**Comment by kosalag** [comment]
Resolved.
