### ISSUE TITLE
Remove PE-R1 tally sheet from tally sheet list make that the report template of PE-CE-RO-V1

### ISSUE THREAD

**Issue by dinukadesilva** [ECLK/results-tabulation#534]

**Comment by dinukadesilva** [comment]
@callkalpa 
I get the report as following. I think there's two additional columns.
<img width="464" alt="Screenshot 2020-04-12 at 1 24 53 AM" src="https://user-images.githubusercontent.com/10680296/79053647-8812f280-7c5c-11ea-940c-d30741663b63.png">

**Comment by dinukadesilva** [comment]
@callkalpa I found one more issue in the tally sheet mapping. I'm making a PR for that.
https://github.com/ECLK/results-tabulation-api/pull/551

**Comment by callkalpa** [comment]
@dinukadesilva columns and some more fixes are with https://github.com/ECLK/results-tabulation-api/pull/552

**Comment by dinukadesilva** [comment]
@callkalpa 
Let me upload an image of an actual form. The generated one has to be like this.
