### ISSUE TITLE
Review authorization flow for Parliament Election

### ISSUE THREAD

**Issue by dinukadesilva** [ECLK/results-tabulation#574]
Each individual role has to be checked with scopes per district (Except for nations and EC users)

**Comment by callkalpa** [comment]
Following spreadsheet contains the analysis with https://tabulations.ecdev.opensource.lk

https://docs.google.com/spreadsheets/d/1vV4FF5Zu2O6clDoAcARaiNtwn2uLApWhSBA2MQouAnc/edit?usp=sharing

**Comment by dinukadesilva** [comment]
This has been completed and further testing is in progress and new issues to be taken for follow up issues
