### ISSUE TITLE
CE-201-PE can be submitted with invalid date time

### ISSUE THREAD

**Issue by callkalpa** [ECLK/results-tabulation#591]
Submit is allowed even without setting a value to `Time of commencement of the count of Postal Votes ballot papers`. Not sure whether this field is mandatory though.

![image](https://user-images.githubusercontent.com/504756/82109840-d93a6880-976b-11ea-83c6-42d5f0e8ebeb.png)

**Comment by dinukadesilva** [comment]
Leaving the date as empty should be doable. But at this screen it should be not "invalid date". I think it should be just blank
