### ISSUE TITLE
Is it good to have the "verify" and "submit" buttons exluded from the tally sheet listing

### ISSUE THREAD

**Issue by dinukadesilva** [ECLK/results-tabulation#601]
I'm just thinking this way since these actions "submit" and "verify" shouldn't be encouraged without looking at the report. What do you think @callkalpa @nshamit @sm1990

**Comment by nshamit** [comment]
@dinukadesilva I'm ok w/ including them inside the report. will help w/ accountability. how will we know from a user interface point of view, that the tally sheet has been submitted if there is no greyed out buttone etc. 

other options include a view and submit button

@callkalpa @sm1990 @dinukadesilva ?

**Comment by dinukadesilva** [comment]
@nshamit 
Tally sheet status is available on the tally sheet list as well as on the preview.
